# Generated by Django 4.0.4 on 2022-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='system',
            name='date',
            field=models.DateField(verbose_name='Date of purchase'),
        ),
    ]
