# Generated by Django 4.0.4 on 2022-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_players_alter_system_options_alter_system_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.AddField(
            model_name='videogame',
            name='players',
            field=models.ManyToManyField(to='main_app.player'),
        ),
    ]
